name: EXVoucherExpansion
version: '1.0.5'
main: org.cptgummiball.eXVoucherExpansion.EXVoucherExpansion
api-version: '1.20'
authors: [ cptgummiball ]
description: A plugin to give kits to players based on chat keywords.
